runtime: python38
env: standard
entrypoint: gunicorn -b :$PORT musical_nft.wsgi:application

handlers:
- url: /static              # new
  static_dir: static/  # new
- url: /.*
  script: auto

runtime_config:
  python_version: 3

